theme: jekyll-theme-tactile
title: Zhicheng Zhang
e-mail: zczhangmas@gmail.com
### Ph.d Student
Department od Information and Physical Sciences   
Graduate School of Information Science and Technology  
Osaka University  
Suita, Osaka 565-0871, Japan

### Curriculum Vitae
Z.C. Zhang received MSc. degree in Mathematics from Guilin University
of Electronic Technology in 2020. From Sep. 2019 to Sep. 2020, he was a
Visiting Student of The University of Kitakyushu, Japan. He is currently a
Doctoral Student at Graduate School of Information Science and Technology,
Osaka University, Suita, Japan.

He is a student member of IET and IEEE.

### Research Interests
multi-agent systems, nonlinear system, control of networked systems, 
sparse control, robust control, optimal control, Reinforcement Learning, etc. 

### Journal Papers
1. Z.C. Zhang, Z.J. Ma and Y. Wang,   
**Partial component consensus of leader-following multi-agent systems via intermittent pinning control**,  
*[Physica A](https://doi.org/10.1016/j.physa.2019.122569), 536 (2019), 122569.* 
