theme: jekyll-theme-tactile
title: Zhicheng Zhang 
e-mail: zczhang@gmail.com
### Master Student
School of Mathematics and Computing Science  
Department of Differntial Equations and Dyanmical Systems  
Guilin University of Electronic Technology  
Guilin 541004, China


### Visiting Student
The Institute of Environmental Science and Technology  
Department of Informatics     
The University of Kitakyushu  
Fukuoka 808-0135, Japan



### Curriculum Vitae
Z.C. Zhang was born in Jiangsu, China, in 1994. He is currently a master student with 
the School of Mathematics and Computing Science, Guilin University of Electronic Technology, 
and is also a visiting student with the Department of Informatics Systems, 
The University of Kitakyushu, Japan.

He is a student member of SICE, IET, SIAM, AAAI and IEEE.

### Research Interests
multi-agent systems, nonlinear system, control of networked systems, 
sparse control, robust control, optimal control, Reinforcement Learning, etc. 

### Journal Papers
1. Z.C. Zhang, Z.J. Ma and Y. Wang,   
**Partial component consensus of leader-following multi-agent systems via intermittent pinning control**,  
*[Physica A](https://doi.org/10.1016/j.physa.2019.122569), 536 (2019), 122569.* 
